/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTransportRouteImport } from './routes/_authenticated.transport'
import { Route as AuthenticatedTelemedicineRouteImport } from './routes/_authenticated.telemedicine'
import { Route as AuthenticatedSymptomCheckerRouteImport } from './routes/_authenticated.symptom-checker'
import { Route as AuthenticatedSpecialistsRouteImport } from './routes/_authenticated.specialists'
import { Route as AuthenticatedSosRouteImport } from './routes/_authenticated.sos'
import { Route as AuthenticatedRecordsRouteImport } from './routes/_authenticated.records'
import { Route as AuthenticatedQueueRouteImport } from './routes/_authenticated.queue'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedPharmacyRouteImport } from './routes/_authenticated.pharmacy'
import { Route as AuthenticatedOutreachRouteImport } from './routes/_authenticated.outreach'
import { Route as AuthenticatedMoreRouteImport } from './routes/_authenticated.more'
import { Route as AuthenticatedMentalRouteImport } from './routes/_authenticated.mental'
import { Route as AuthenticatedMaternalRouteImport } from './routes/_authenticated.maternal'
import { Route as AuthenticatedInsuranceRouteImport } from './routes/_authenticated.insurance'
import { Route as AuthenticatedIncidentRouteImport } from './routes/_authenticated.incident'
import { Route as AuthenticatedImmunizationRouteImport } from './routes/_authenticated.immunization'
import { Route as AuthenticatedHospitalsRouteImport } from './routes/_authenticated.hospitals'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated.home'
import { Route as AuthenticatedEducationRouteImport } from './routes/_authenticated.education'
import { Route as AuthenticatedBloodDonorsRouteImport } from './routes/_authenticated.blood-donors'
import { Route as AuthenticatedBloodBankRouteImport } from './routes/_authenticated.blood-bank'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated.appointments'
import { Route as AuthenticatedAmbulanceRouteImport } from './routes/_authenticated.ambulance'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedDoctorsIdRouteImport } from './routes/_authenticated.doctors.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransportRoute = AuthenticatedTransportRouteImport.update({
  id: '/_authenticated/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTelemedicineRoute =
  AuthenticatedTelemedicineRouteImport.update({
    id: '/_authenticated/telemedicine',
    path: '/telemedicine',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSymptomCheckerRoute =
  AuthenticatedSymptomCheckerRouteImport.update({
    id: '/_authenticated/symptom-checker',
    path: '/symptom-checker',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSpecialistsRoute =
  AuthenticatedSpecialistsRouteImport.update({
    id: '/_authenticated/specialists',
    path: '/specialists',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSosRoute = AuthenticatedSosRouteImport.update({
  id: '/_authenticated/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRecordsRoute = AuthenticatedRecordsRouteImport.update({
  id: '/_authenticated/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQueueRoute = AuthenticatedQueueRouteImport.update({
  id: '/_authenticated/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/_authenticated/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPharmacyRoute = AuthenticatedPharmacyRouteImport.update({
  id: '/_authenticated/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOutreachRoute = AuthenticatedOutreachRouteImport.update({
  id: '/_authenticated/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMoreRoute = AuthenticatedMoreRouteImport.update({
  id: '/_authenticated/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMentalRoute = AuthenticatedMentalRouteImport.update({
  id: '/_authenticated/mental',
  path: '/mental',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMaternalRoute = AuthenticatedMaternalRouteImport.update({
  id: '/_authenticated/maternal',
  path: '/maternal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInsuranceRoute = AuthenticatedInsuranceRouteImport.update({
  id: '/_authenticated/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIncidentRoute = AuthenticatedIncidentRouteImport.update({
  id: '/_authenticated/incident',
  path: '/incident',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedImmunizationRoute =
  AuthenticatedImmunizationRouteImport.update({
    id: '/_authenticated/immunization',
    path: '/immunization',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedHospitalsRoute = AuthenticatedHospitalsRouteImport.update({
  id: '/_authenticated/hospitals',
  path: '/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/_authenticated/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEducationRoute = AuthenticatedEducationRouteImport.update({
  id: '/_authenticated/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBloodDonorsRoute =
  AuthenticatedBloodDonorsRouteImport.update({
    id: '/_authenticated/blood-donors',
    path: '/blood-donors',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedBloodBankRoute = AuthenticatedBloodBankRouteImport.update({
  id: '/_authenticated/blood-bank',
  path: '/blood-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/_authenticated/appointments',
    path: '/appointments',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAmbulanceRoute = AuthenticatedAmbulanceRouteImport.update({
  id: '/_authenticated/ambulance',
  path: '/ambulance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_authenticated/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDoctorsIdRoute = AuthenticatedDoctorsIdRouteImport.update({
  id: '/_authenticated/doctors/$id',
  path: '/doctors/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ambulance': typeof AuthenticatedAmbulanceRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/blood-bank': typeof AuthenticatedBloodBankRoute
  '/blood-donors': typeof AuthenticatedBloodDonorsRoute
  '/education': typeof AuthenticatedEducationRoute
  '/home': typeof AuthenticatedHomeRoute
  '/hospitals': typeof AuthenticatedHospitalsRoute
  '/immunization': typeof AuthenticatedImmunizationRoute
  '/incident': typeof AuthenticatedIncidentRoute
  '/insurance': typeof AuthenticatedInsuranceRoute
  '/maternal': typeof AuthenticatedMaternalRoute
  '/mental': typeof AuthenticatedMentalRoute
  '/more': typeof AuthenticatedMoreRoute
  '/outreach': typeof AuthenticatedOutreachRoute
  '/pharmacy': typeof AuthenticatedPharmacyRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/records': typeof AuthenticatedRecordsRoute
  '/sos': typeof AuthenticatedSosRoute
  '/specialists': typeof AuthenticatedSpecialistsRoute
  '/symptom-checker': typeof AuthenticatedSymptomCheckerRoute
  '/telemedicine': typeof AuthenticatedTelemedicineRoute
  '/transport': typeof AuthenticatedTransportRoute
  '/doctors/$id': typeof AuthenticatedDoctorsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ambulance': typeof AuthenticatedAmbulanceRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/blood-bank': typeof AuthenticatedBloodBankRoute
  '/blood-donors': typeof AuthenticatedBloodDonorsRoute
  '/education': typeof AuthenticatedEducationRoute
  '/home': typeof AuthenticatedHomeRoute
  '/hospitals': typeof AuthenticatedHospitalsRoute
  '/immunization': typeof AuthenticatedImmunizationRoute
  '/incident': typeof AuthenticatedIncidentRoute
  '/insurance': typeof AuthenticatedInsuranceRoute
  '/maternal': typeof AuthenticatedMaternalRoute
  '/mental': typeof AuthenticatedMentalRoute
  '/more': typeof AuthenticatedMoreRoute
  '/outreach': typeof AuthenticatedOutreachRoute
  '/pharmacy': typeof AuthenticatedPharmacyRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/records': typeof AuthenticatedRecordsRoute
  '/sos': typeof AuthenticatedSosRoute
  '/specialists': typeof AuthenticatedSpecialistsRoute
  '/symptom-checker': typeof AuthenticatedSymptomCheckerRoute
  '/telemedicine': typeof AuthenticatedTelemedicineRoute
  '/transport': typeof AuthenticatedTransportRoute
  '/doctors/$id': typeof AuthenticatedDoctorsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ambulance': typeof AuthenticatedAmbulanceRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/blood-bank': typeof AuthenticatedBloodBankRoute
  '/_authenticated/blood-donors': typeof AuthenticatedBloodDonorsRoute
  '/_authenticated/education': typeof AuthenticatedEducationRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/hospitals': typeof AuthenticatedHospitalsRoute
  '/_authenticated/immunization': typeof AuthenticatedImmunizationRoute
  '/_authenticated/incident': typeof AuthenticatedIncidentRoute
  '/_authenticated/insurance': typeof AuthenticatedInsuranceRoute
  '/_authenticated/maternal': typeof AuthenticatedMaternalRoute
  '/_authenticated/mental': typeof AuthenticatedMentalRoute
  '/_authenticated/more': typeof AuthenticatedMoreRoute
  '/_authenticated/outreach': typeof AuthenticatedOutreachRoute
  '/_authenticated/pharmacy': typeof AuthenticatedPharmacyRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/queue': typeof AuthenticatedQueueRoute
  '/_authenticated/records': typeof AuthenticatedRecordsRoute
  '/_authenticated/sos': typeof AuthenticatedSosRoute
  '/_authenticated/specialists': typeof AuthenticatedSpecialistsRoute
  '/_authenticated/symptom-checker': typeof AuthenticatedSymptomCheckerRoute
  '/_authenticated/telemedicine': typeof AuthenticatedTelemedicineRoute
  '/_authenticated/transport': typeof AuthenticatedTransportRoute
  '/_authenticated/doctors/$id': typeof AuthenticatedDoctorsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ambulance'
    | '/appointments'
    | '/blood-bank'
    | '/blood-donors'
    | '/education'
    | '/home'
    | '/hospitals'
    | '/immunization'
    | '/incident'
    | '/insurance'
    | '/maternal'
    | '/mental'
    | '/more'
    | '/outreach'
    | '/pharmacy'
    | '/profile'
    | '/queue'
    | '/records'
    | '/sos'
    | '/specialists'
    | '/symptom-checker'
    | '/telemedicine'
    | '/transport'
    | '/doctors/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ambulance'
    | '/appointments'
    | '/blood-bank'
    | '/blood-donors'
    | '/education'
    | '/home'
    | '/hospitals'
    | '/immunization'
    | '/incident'
    | '/insurance'
    | '/maternal'
    | '/mental'
    | '/more'
    | '/outreach'
    | '/pharmacy'
    | '/profile'
    | '/queue'
    | '/records'
    | '/sos'
    | '/specialists'
    | '/symptom-checker'
    | '/telemedicine'
    | '/transport'
    | '/doctors/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated/admin'
    | '/_authenticated/ambulance'
    | '/_authenticated/appointments'
    | '/_authenticated/blood-bank'
    | '/_authenticated/blood-donors'
    | '/_authenticated/education'
    | '/_authenticated/home'
    | '/_authenticated/hospitals'
    | '/_authenticated/immunization'
    | '/_authenticated/incident'
    | '/_authenticated/insurance'
    | '/_authenticated/maternal'
    | '/_authenticated/mental'
    | '/_authenticated/more'
    | '/_authenticated/outreach'
    | '/_authenticated/pharmacy'
    | '/_authenticated/profile'
    | '/_authenticated/queue'
    | '/_authenticated/records'
    | '/_authenticated/sos'
    | '/_authenticated/specialists'
    | '/_authenticated/symptom-checker'
    | '/_authenticated/telemedicine'
    | '/_authenticated/transport'
    | '/_authenticated/doctors/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAmbulanceRoute: typeof AuthenticatedAmbulanceRoute
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedBloodBankRoute: typeof AuthenticatedBloodBankRoute
  AuthenticatedBloodDonorsRoute: typeof AuthenticatedBloodDonorsRoute
  AuthenticatedEducationRoute: typeof AuthenticatedEducationRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedHospitalsRoute: typeof AuthenticatedHospitalsRoute
  AuthenticatedImmunizationRoute: typeof AuthenticatedImmunizationRoute
  AuthenticatedIncidentRoute: typeof AuthenticatedIncidentRoute
  AuthenticatedInsuranceRoute: typeof AuthenticatedInsuranceRoute
  AuthenticatedMaternalRoute: typeof AuthenticatedMaternalRoute
  AuthenticatedMentalRoute: typeof AuthenticatedMentalRoute
  AuthenticatedMoreRoute: typeof AuthenticatedMoreRoute
  AuthenticatedOutreachRoute: typeof AuthenticatedOutreachRoute
  AuthenticatedPharmacyRoute: typeof AuthenticatedPharmacyRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedQueueRoute: typeof AuthenticatedQueueRoute
  AuthenticatedRecordsRoute: typeof AuthenticatedRecordsRoute
  AuthenticatedSosRoute: typeof AuthenticatedSosRoute
  AuthenticatedSpecialistsRoute: typeof AuthenticatedSpecialistsRoute
  AuthenticatedSymptomCheckerRoute: typeof AuthenticatedSymptomCheckerRoute
  AuthenticatedTelemedicineRoute: typeof AuthenticatedTelemedicineRoute
  AuthenticatedTransportRoute: typeof AuthenticatedTransportRoute
  AuthenticatedDoctorsIdRoute: typeof AuthenticatedDoctorsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transport': {
      id: '/_authenticated/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof AuthenticatedTransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/telemedicine': {
      id: '/_authenticated/telemedicine'
      path: '/telemedicine'
      fullPath: '/telemedicine'
      preLoaderRoute: typeof AuthenticatedTelemedicineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/symptom-checker': {
      id: '/_authenticated/symptom-checker'
      path: '/symptom-checker'
      fullPath: '/symptom-checker'
      preLoaderRoute: typeof AuthenticatedSymptomCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/specialists': {
      id: '/_authenticated/specialists'
      path: '/specialists'
      fullPath: '/specialists'
      preLoaderRoute: typeof AuthenticatedSpecialistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sos': {
      id: '/_authenticated/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof AuthenticatedSosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/records': {
      id: '/_authenticated/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof AuthenticatedRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/queue': {
      id: '/_authenticated/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AuthenticatedQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pharmacy': {
      id: '/_authenticated/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof AuthenticatedPharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/outreach': {
      id: '/_authenticated/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof AuthenticatedOutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/more': {
      id: '/_authenticated/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AuthenticatedMoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mental': {
      id: '/_authenticated/mental'
      path: '/mental'
      fullPath: '/mental'
      preLoaderRoute: typeof AuthenticatedMentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/maternal': {
      id: '/_authenticated/maternal'
      path: '/maternal'
      fullPath: '/maternal'
      preLoaderRoute: typeof AuthenticatedMaternalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/insurance': {
      id: '/_authenticated/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof AuthenticatedInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/incident': {
      id: '/_authenticated/incident'
      path: '/incident'
      fullPath: '/incident'
      preLoaderRoute: typeof AuthenticatedIncidentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/immunization': {
      id: '/_authenticated/immunization'
      path: '/immunization'
      fullPath: '/immunization'
      preLoaderRoute: typeof AuthenticatedImmunizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/hospitals': {
      id: '/_authenticated/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof AuthenticatedHospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/education': {
      id: '/_authenticated/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof AuthenticatedEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/blood-donors': {
      id: '/_authenticated/blood-donors'
      path: '/blood-donors'
      fullPath: '/blood-donors'
      preLoaderRoute: typeof AuthenticatedBloodDonorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/blood-bank': {
      id: '/_authenticated/blood-bank'
      path: '/blood-bank'
      fullPath: '/blood-bank'
      preLoaderRoute: typeof AuthenticatedBloodBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ambulance': {
      id: '/_authenticated/ambulance'
      path: '/ambulance'
      fullPath: '/ambulance'
      preLoaderRoute: typeof AuthenticatedAmbulanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/doctors/$id': {
      id: '/_authenticated/doctors/$id'
      path: '/doctors/$id'
      fullPath: '/doctors/$id'
      preLoaderRoute: typeof AuthenticatedDoctorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAmbulanceRoute: AuthenticatedAmbulanceRoute,
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedBloodBankRoute: AuthenticatedBloodBankRoute,
  AuthenticatedBloodDonorsRoute: AuthenticatedBloodDonorsRoute,
  AuthenticatedEducationRoute: AuthenticatedEducationRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedHospitalsRoute: AuthenticatedHospitalsRoute,
  AuthenticatedImmunizationRoute: AuthenticatedImmunizationRoute,
  AuthenticatedIncidentRoute: AuthenticatedIncidentRoute,
  AuthenticatedInsuranceRoute: AuthenticatedInsuranceRoute,
  AuthenticatedMaternalRoute: AuthenticatedMaternalRoute,
  AuthenticatedMentalRoute: AuthenticatedMentalRoute,
  AuthenticatedMoreRoute: AuthenticatedMoreRoute,
  AuthenticatedOutreachRoute: AuthenticatedOutreachRoute,
  AuthenticatedPharmacyRoute: AuthenticatedPharmacyRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedQueueRoute: AuthenticatedQueueRoute,
  AuthenticatedRecordsRoute: AuthenticatedRecordsRoute,
  AuthenticatedSosRoute: AuthenticatedSosRoute,
  AuthenticatedSpecialistsRoute: AuthenticatedSpecialistsRoute,
  AuthenticatedSymptomCheckerRoute: AuthenticatedSymptomCheckerRoute,
  AuthenticatedTelemedicineRoute: AuthenticatedTelemedicineRoute,
  AuthenticatedTransportRoute: AuthenticatedTransportRoute,
  AuthenticatedDoctorsIdRoute: AuthenticatedDoctorsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
